[package]
name = "firere/roact-hooks"
description = "An implementation of hooks in Roact, with some extra features"
version = "0.5.2"
license = "MPL-2.0"
authors = ["Kampfkarren", "Firere"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
